# Generated by Django 5.0.2 on 2024-02-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='profession',
            field=models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='myapp.profession'),
        ),
    ]
